FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование кода приложения
COPY . .

# Команда будет переопределена в docker-compose.yml
CMD ["celery", "-A", "transactional_system", "worker", "--loglevel=info"]

