# Generated by Django 4.2.7 on 2025-12-05 18:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        db_index=True, help_text="ID пользователя", unique=True
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Баланс кошелька",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Сумма транзакции",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("transfer", "Перевод"), ("commission", "Комиссия")],
                        default="transfer",
                        help_text="Тип транзакции",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        help_text="Статус транзакции",
                        max_length=20,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Сумма комиссии",
                        max_digits=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кошелек отправителя (null для комиссии)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "to_wallet",
                    models.ForeignKey(
                        help_text="Кошелек получателя",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_wallet", "created_at"],
                        name="transaction_from_wa_16d426_idx",
                    ),
                    models.Index(
                        fields=["to_wallet", "created_at"],
                        name="transaction_to_wall_2918f3_idx",
                    ),
                ],
            },
        ),
    ]
